excluded:
  - DocuScan/DocuScan/Resources/

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - force_unwrapping
  - force_cast
  - implicitly_unwrapped_optional
  - empty_count
  - closure_spacing

force_unwrapping: error
force_cast: error

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500
